sudo: false

language: go

go:
  - 1.6.2

install:
  - go get -v github.com/go-ini/ini
  - go get -v github.com/jmespath/go-jmespath
  - go get -v github.com/golib/assert

before_script:

script:
  - echo "$TRAVIS_BRANCH"@"$TRAVIS_COMMIT"
  - cd $TRAVIS_BUILD_DIR && source env.sh
  - echo $GOPATH
  - make travis
